# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
#  ldap-service:
#    container_name: ldap-service
#    image: dwimberger/ldap-ad-it
#    ports:
#      - "10389:10389"
#  postgresql_keycloak:
#    container_name: postgresql_keycloak
#    image: postgres:12
#    ports:
#      - "5433:5433"
#    expose:
#      - "5433"
#    command: -p 5433
#    environment:
#      POSTGRES_PASSWORD: root
#      POSTGRES_USER: root
#      POSTGRES_DB: keycloak
#  keycloak:
#    depends_on:
#      - "postgresql_keycloak"
#    container_name: keycloak
#    image: jboss/keycloak
#    ports:
#      - "8080:8080"
#    environment:
#      DB_VENDOR: "postgres"
#      DB_ADDR: postgresql_keycloak
#      DB_PORT: "5433"
#      DB_USER: "root"
#      DB_PASSWORD: "root"
#      KEYCLOAK_USER: "keycloak"
#      KEYCLOAK_PASSWORD: "keycloak"
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  horusec_postgresql:
    container_name: horusec_postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      POSTGRES_PASSWORD: root # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres2/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5
  horusec-messages:
    build:
      context: ../../messages
      dockerfile: ./deployments/dockerfiles/Dockerfile.dev
    depends_on:
      - "rabbit"
    restart: always
    container_name: horusec-messages
    network_mode: "host"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_PORT: "8002"
      HORUSEC_BROKER_HOST: "10.254.64.251"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "infosec_2024" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_SMTP_ADDRESS: "sandbox.smtp.mailtrap.io"
      HORUSEC_SMTP_USERNAME: "6805246e6f1654" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_SMTP_PASSWORD: "0b4aeeda9d0e28" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_SMTP_HOST: "sandbox.smtp.mailtrap.io"
      HORUSEC_SMTP_PORT: "2525"
      HORUSEC_EMAIL_FROM: "infosec@finaccel.co"
  horusec-auth:
    build:
      context: ../../auth
      dockerfile: ./deployments/dockerfiles/Dockerfile.dev
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
    restart: always
    container_name: horusec-auth
    network_mode: "host"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_PORT: "8006"
      HORUSEC_GRPC_PORT: "8050"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@10.254.64.251:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "true"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_KEYCLOAK_BASE_PATH: ""
      HORUSEC_KEYCLOAK_CLIENT_ID: "" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_KEYCLOAK_CLIENT_SECRET: "" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_KEYCLOAK_REALM: "" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_LDAP_BASE: "dc=wimpi,dc=net"
      HORUSEC_LDAP_HOST: "10.254.64.251"
      HORUSEC_LDAP_PORT: "10389"
      HORUSEC_LDAP_USESSL: "false"
      HORUSEC_LDAP_SKIP_TLS: "true"
      HORUSEC_LDAP_INSECURE_SKIP_VERIFY: "true"
      HORUSEC_LDAP_BINDDN: "uid=admin,ou=system"
      HORUSEC_LDAP_BINDPASSWORD: "secret" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_LDAP_USERFILTER: "(sAMAccountName=%s)"
      HORUSEC_LDAP_ADMIN_GROUP: "admin" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_APPLICATION_ADMIN_DATA: "{\"username\": \"horusec-admin\", \"email\":\"horusec-admin@example.com\", \"password\":\"Devpass0*\"}" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_ENABLE_DEFAULT_USER: "true"
      HORUSEC_DEFAULT_USER_DATA: "{\"username\": \"dev\", \"email\":\"dev@example.com\", \"password\":\"Devpass0*\"}" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_AUTH_TYPE: "horusec"
      HORUSEC_BROKER_HOST: "10.254.64.251"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "infosec_2024" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DISABLE_EMAILS: "true"
      HORUSEC_AUTH_URL: "10.254.64.251:8006"
      HORUSEC_MANAGER_URL: "10.254.64.251:8043"
  horusec-core:
    build:
      context: ../../core
      dockerfile: ./deployments/dockerfiles/Dockerfile.dev
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-core
    network_mode: "host"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_PORT: "8003"
      HORUSEC_DISABLED_BROKER: "true"
      HORUSEC_BROKER_HOST: "10.254.64.251"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "infosec_2024" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@10.254.64.251:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "true"
      HORUSEC_GRPC_AUTH_URL: "localhost:8050"
      HORUSEC_MANAGER_URL: "10.254.64.251:8043"
  horusec-analytic:
    build:
      context: ../../analytic
      dockerfile: ./deployments/dockerfiles/Dockerfile.dev
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-analytic
    network_mode: "host"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_PORT: "8005"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@10.254.64.251:5432/horusec_analytic_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "true"
      HORUSEC_GRPC_AUTH_URL: "localhost:8050"
      HORUSEC_BROKER_HOST: "10.254.64.251"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "infosec_2024" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
  horusec-api:
    build:

      context: ../../api
      dockerfile: ./deployments/dockerfiles/Dockerfile.dev
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-api
    network_mode: "host"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_PORT: "8000"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@10.254.64.251:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "true"
      HORUSEC_GRPC_AUTH_URL: "localhost:8050"
      HORUSEC_BROKER_HOST: "10.254.64.251"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "infosec_2024" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
  horusec-vulnerability:
    build:
      context: ../../vulnerability
      dockerfile: ./deployments/dockerfiles/Dockerfile.dev
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-vulnerability
    network_mode: "host"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_PORT: "8001"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@10.254.64.251:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "true"
      HORUSEC_GRPC_AUTH_URL: "localhost:8050"
      HORUSEC_BROKER_HOST: "10.254.64.251"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "infosec_2024" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
  horusec-webhook:
   build:
     context: ../../webhook
     dockerfile: ./deployments/dockerfiles/Dockerfile.dev
   depends_on:
     - "rabbit"
     - "horusec_postgresql"
   restart: always
   container_name: horusec-webhook
   network_mode: "host"
   volumes:
     - ../:/usr/app
   environment:
     HORUSEC_PORT: "8004"
     HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@10.254.64.251:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
     HORUSEC_DATABASE_SQL_LOG_MODE: "true"
     HORUSEC_GRPC_AUTH_URL: "localhost:8050"
     HORUSEC_BROKER_HOST: "10.254.64.251"
     HORUSEC_BROKER_PORT: "5672"
     HORUSEC_BROKER_USERNAME: "guest"
     HORUSEC_BROKER_PASSWORD: "infosec_2024"
  horusec-manager:
    build:
      context: ../../manager
      dockerfile: ./deployments/dockerfiles/Dockerfile
    restart: always
    container_name: horusec-manager
    ports:
      - "8043:8080"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_ENDPOINT_API: "http:\/\/10.254.64.251:8000"
      HORUSEC_ENDPOINT_ANALYTIC: "http:\/\/10.254.64.251:8005"
      HORUSEC_ENDPOINT_CORE: "http:\/\/10.254.64.251:8003"
      HORUSEC_ENDPOINT_WEBHOOK: "http:\/\/10.254.64.251:8003"
      HORUSEC_ENDPOINT_AUTH: "http:\/\/10.254.64.251:8006"
      HORUSEC_ENDPOINT_VULNERABILITY: "http:\/\/10.254.64.251:8001"
      REACT_APP_HORUSEC_ENDPOINT_API: "http:\/\/10.254.64.251:8000"
      REACT_APP_HORUSEC_ENDPOINT_ANALYTIC: "http:\/\/10.254.64.251:8005"
      REACT_APP_HORUSEC_ENDPOINT_CORE: "http:\/\/10.254.64.251:8003"
      REACT_APP_HORUSEC_ENDPOINT_WEBHOOK: "http:\/\/10.254.64.251:8003"
      REACT_APP_HORUSEC_ENDPOINT_AUTH: "http:\/\/10.254.64.251:8006"
      REACT_APP_HORUSEC_ENDPOINT_VULNERABILITY: "http:\/\/10.254.64.251:8001"
      REACT_APP_KEYCLOAK_BASE_PATH: ""
      REACT_APP_KEYCLOAK_CLIENT_ID: ""
      REACT_APP_KEYCLOAK_REALM: ""
      REACT_APP_MICROFRONTEND_PUBLIC_PATH: ""
      REACT_APP_HORUSEC_MANAGER_THEME: ""
